# Generated by Django 3.2.6 on 2021-12-09 12:32

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job Title', max_length=200)),
                ('description', models.TextField(help_text='Job Description')),
                ('company', models.CharField(help_text='Company Name', max_length=200)),
                ('location', models.CharField(help_text='Location', max_length=200)),
                ('link', models.URLField(help_text='Link to Job')),
                ('date', models.DateField(help_text='Publish Date')),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='Broken',
        ),
        migrations.RemoveField(
            model_name='product',
            name='change',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mod',
        ),
        migrations.DeleteModel(
            name='broke',
        ),
        migrations.DeleteModel(
            name='changed',
        ),
        migrations.DeleteModel(
            name='color',
        ),
        migrations.DeleteModel(
            name='mod',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
