# Generated by Django 3.2.6 on 2022-01-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='Salary'),
        ),
    ]
